env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "prefer-const": 0,
  "no-use-before-define": 0,
  "arrow-parens": 0,
  "object-curly-newline": 0
}
